extends: airbnb
parser: babel-eslint
plugins:
  - flowtype
env:
  browser: true
globals:
  ga: false
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      FunctionDeclaration:
        parameters: first
  curly: off
  comma-dangle: off
  prefer-destructuring: off
  default-case: off
  function-paren-newline: off
  camelcase: off

  no-lonely-if: off
  no-continue: off
  no-bitwise: off
  no-param-reassign: off
  no-use-before-define: off
  no-shadow: warn
  no-nested-ternary: off
  no-restricted-globals: off
  no-restricted-properties: off

  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-closing-tag-location: off
  react/prop-types: off
  react/jsx-wrap-multilines: off
  react/jsx-tag-spacing: off
  react/jsx-filename-extension: off
  react/jsx-no-bind: off

  import/no-named-as-default-member: off
  import/prefer-default-export: off

  object-curly-spacing: off
  object-curly-newline: off

  jsx-a11y/alt-text: off
